name: Github Pages
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  release:
    if: github.repository == 'zoofiio/zoofi-ui' && contains(github.event.head_commit.message, '[release]') 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies & build
        run: |
          pnpm install --frozen-lockfile    
          pnpm build

      - name: Deploy Gh-Pages 🚀
        uses: XueMoMo/actions-gh-pages@v4.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          keep_files: 'beta/*'
          cname: zoofi.io
  beta:
    if: github.repository == 'zoofiio/zoofi-ui' && contains(github.event.head_commit.message, '[beta]') 
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Install dependencies & build
        env: 
          NEXT_PUBLIC_BASE_PATH: /beta
        run: |
          pnpm install --frozen-lockfile   
          pnpm build

      - name: Deploy Gh-Pages 🚀
        uses: XueMoMo/actions-gh-pages@v4.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          destination_dir: beta
          
          