name: Github Pages Staging
on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  build:
    if: github.repository == 'zoofiio/zoofi-ui'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install --frozen-lockfile

      - name: Build for production
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build

      - name: Deploy Gh-Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DK_STAGING }}
          external_repository: zoofiio/zoofi-ui-staging
          publish_branch: main
          publish_dir: ./out
          cname: staging.wand.fi