name: Github Pages Beta Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    if: github.repository == 'zoofiio/zoofi-ui'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Build for production
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build

      - name: Deploy Gh-Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_BETA }}
          external_repository: zoofiio/zoofi-ui-beta
          publish_branch: main
          publish_dir: ./out
          cname: beta.zoofi.xyz