name: IPFS Beta Deploy
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - dev

jobs:
  build:
    if: github.repository == 'zoofiio/zoofi-ui'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Build for production
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build

      - name: Pin to IPFS
        id: upload
        uses: crustio/ipfs-upload-action@v2.0.4
        with:
          path: './out'
          seeds: ${{ secrets.CRUST_SEEDS }}
          gateway: 'https://gw.crustfiles.net'

      # - name: Pin to IPFS
      #   id: upload
      #   uses: crustio/ipfs-upload-action@v2.0.2
      #   with:
      #     path: './out'
      #     seeds: ${{ secrets.CRUST_SEEDS }}
      #     gateway: 'https://gw.crustfiles.net'
      # - name: Convert CIDv0 to CIDv1
      #   id: convert-cidv0
      #   uses: uniswap/convert-cidv0-cidv1@v1.0.0
      #   with:
      #     cidv0: ${{ steps.upload.outputs.hash }}

      - name: Place storage order on Crust
        uses: crustio/ipfs-crust-action@v2.0.6
        continue-on-error: true
        timeout-minutes: 2
        with:
          cid: ${{ steps.upload.outputs.hash }}
          seeds: ${{ secrets.CRUST_SEEDS }}

      - name: Update DNS with new IPFS hash
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: 'ipfs-beta.wand.fi'
          RECORD_NAME: '_dnslink'
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        uses: textileio/cloudflare-update-dnslink@master
        with:
          cid: ${{ steps.upload.outputs.hash }}